# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  push:
    branches: 
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-to-npm:
    name: 'Publish to NPM'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.SDHANKAR_NPM_TOKEN }}" > .npmrc
          yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SDHANKAR_NPM_TOKEN }}
      - name: Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SDHANKAR_NPM_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.SDHANKAR_NPM_TOKEN }}" > ~/.npmrc
          npm config set registry https://npm.pkg.github.com/SunRun
          npm config set always-auth true
          sudo mkdir ~/.npm || true
          sudo chown -R $USER:$GROUP ~/.npm || true
          sudo chown -R $USER:$GROUP ~/.config || true
          npm publish --verbose